### ISSUE TITLE
Selecting music local/soundcloud doesnt automatically play it

### ISSUE THREAD

**Issue by icss91** [harjot-oberai/MusicStreamer#10]
So, when tapping on a song, the playback doesnt start, you need to press the pause/play button for the song to start playing

**Comment by Dirkstaal** [comment]
Its already been sorted out use the latest project

**Comment by harjot-oberai** [comment]
I just tested the app on a marshmallow device and i did not encounter any such issue.
Please confirm that the problem is solved. if not, please comment here.
I have never encountered this problem, may be i'm missing something.

**Comment by icss91** [comment]
It still doesnt work on my device (Nexus 5/6.0.1), it says "starting" but it doesnt play until i pause/play

**Comment by Dirkstaal** [comment]
Keep your patience :) he is very busy

**Comment by harjot-oberai** [comment]
@icss91 : I'm looking into the issue, problem is that i am not experiencing the problem on any of marshmallow device, this makes it a very weird problem. Will try to find a solution by end of this week.
:+1:

**Comment by icss91** [comment]
Cool!

**Comment by icss91** [comment]
This problem still persists with the latest updates.
